#!/bin/sh

. /root/box/conf/dmz

WAN_IP=`ifconfig $WAN_DEV | awk '/inet addr:/ { sub(/addr:/, ""); print $2 }'`

if [ 1 -ne "`iptables -t nat -L PREROUTING | grep "$WAN_IP" | grep "$DMZ_IP" | grep DNAT | wc -l`" ]; then
	for num in `iptables -t nat -L PREROUTING --line-numbers | grep "$WAN_IP" | grep DNAT | awk '{print $1}' | sort -rn`; do
		iptables -t nat -D PREROUTING $num
	done
	
	# When set to prerouting_rule, the router is not accessible from WAN.
	iptables -t nat -A PREROUTING -s "$DMZ_IP"/24 -d "$WAN_IP" -j DNAT --to "$DMZ_IP" -i "$LAN_DEV"
	
	# When set to FORWARD, the DMZ is not accessible from LAN.
	iptables -A forwarding_rule -d "$DMZ_IP" -j ACCEPT -i "$LAN_DEV"
	
	iptables -t nat -A POSTROUTING -s "$DMZ_IP"/24 -d "$DMZ_IP" -j MASQUERADE -o "$LAN_DEV"
else
	echo 'Already updated' >&2
fi
